language: python
notifications:
  irc:
    - "irc.freenode.net#suplemon"
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

# command to install dependencies
install:
  - "pip install -r requirements-dev.txt --use-mirrors"

# Not Implemented
# ignore=E501,W291,W293"
# command to run tests
#script: "python setup.py nosetests"
script:
  - "flake8 suplemon --max-line-length=120"
